name: Build and publish to artifactory

on:
  # Triggers the workflow on push to master
  push:
    branches: [master]
    tags: ['*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'

      - name: Install dependencies
        run: bundle install

      - name: Install gem release and bump version
        run: |
          gem install gem-release
          gem bump

      - name: Build gem
        run: bundle exec rake build

      - name: Push gem to Artifactory
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        run: |
          gem push pkg/*.gem -k rubygems --host https://artifactory.limepoint.engineering/artifactory/api/gems/opschain
          gem push pkg/*.gem -k rubygems --host https://artifactory.limepoint.engineering/artifactory/api/gems/opschain-release
